routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'UserController@index')->name('users.index');
Route::post('/users', 'UserController@store')->name('users.store');

Route::resource('users', 'UserController')->only([
    'create', 'update', 'edit'
]);

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Entities\User;
use App\Http\Requests\StoreUserRequest;
use App\Http\Requests\UpdateUserRequest;
use App\Http\Resources\UserResource;
use App\Services\UserService;
use Illuminate\Http\Request;

class UserController extends Controller
{
    protected $service;

    function __construct(UserService $service)
    {
        $this->service = $service;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $users = UserResource::collection($this->service->listUsers($request->search));

        $search = $request->search;

        return view('users.index', compact(['users', 'search']));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        return view('users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreUserRequest $request)
    {
        $this->service->storeUser($request);

        return redirect()->route('users.index')
            ->with('success',trans('auth.user_created'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $user = new UserResource($user);

        return view('users.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateUserRequest $request, User $user)
    {
        $this->service->updateUser($user, $request);

        return redirect()->route('users.index')
            ->with('success',trans('auth.user_updated'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        //
    }
}

resources/views/template.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Home</title>
        <!-- Boostrap -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Raleway:100,600" rel="stylesheet" type="text/css">

        <!-- Styles -->
        <style>
            html, body {
                background-color: #fff;
                color: #000;
                font-color: #000;
                font-family: 'Raleway', sans-serif;
                font-weight: 100;
                height: 100vh;
                margin: 0;
            }

            .content {
                text-align: center;
            }

            .title {
                font-size: 84px;
            }
        </style>

        @yield('header')
    </head>
    <body>
        <div class="container">
            <div class="row content">
                <div class="col-md-12">
                    <div class="title">
                        Usuários
                    </div>

                    <div class="links">
                        <a class="btn btn-default" role="button" href="{{ route('users.index') }}">Ver todos</a>
                        <a class="btn btn-default" role="button" href="{{ route('users.create') }}">Criar usuario</a>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    @yield('main')
                </div>
            </div>
          </div>
        </div>

        <script
          src="https://code.jquery.com/jquery-3.3.1.min.js"
          integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
          crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

        @yield('scripts')
    </body>
</html>

resources/views/users/create.blade.php
@extends('template')

@section('main')
    <div class="text-center">
        <h2>Criar usuário</h2>
    </div>
    <div class="row">
        <div class="col-md-12">
            <form no-validate class="form-horizontal" method="POST" action="{{ route('users.store') }}" enctype="multipart/form-data">
                @include('users.form')
            </form>
        </div>
    </div>
@stop

resources/views/users/edit.blade.php
@extends('template')

@section('main')
    <div class="text-center">
        <h2>Criar usuário</h2>
    </div>
    <div class="row">
        <div class="col-md-12">
            <form no-validate class="form-horizontal" method="POST" action="{{ route('users.update', $user->id) }}" enctype="multipart/form-data">
                <input name="_method" type="hidden" value="PATCH">
                @include('users.form')
            </form>
        </div>
    </div>
@stop

resources/views/users/form.blade.php
{{ csrf_field() }}
<div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
    <label for="name">Nome</label>
    <input type="text" class="form-control" name="name" id="name" placeholder="Nome" value="{{ isset($user) ? $user->name : old('name') }}">
    @if ($errors->has('name'))
        <span class="help-block">
            <strong>{{ $errors->first('name') }}</strong>
        </span>
    @endif
</div>
<div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
    <label for="email">E-mail</label>
    <input type="email" class="form-control" name="email" id="email" placeholder="E-mail" value="{{ isset($user) ? $user->email : old('email') }}">
    @if ($errors->has('email'))
        <span class="help-block">
            <strong>{{ $errors->first('email') }}</strong>
        </span>
    @endif
</div>
<div class="form-group{{ $errors->has('document') ? ' has-error' : '' }}">
    <label for="document">Cpf</label>
    <input type="text" class="form-control" name="document" id="document" placeholder="Cpf" value="{{ isset($user) ? $user->document : old('document') }}">
    @if ($errors->has('document'))
        <span class="help-block">
            <strong>{{ $errors->first('document') }}</strong>
        </span>
    @endif
</div>
<div class="form-group{{ $errors->has('birthday') ? ' has-error' : '' }}">
    <label for="birthday">Data de nascimento</label>
    <input type="date" class="form-control" name="birthday" id="birthday" placeholder="Data de nascimento" value="{{ isset($user) ? $user->birthday : old('birthday') }}">
    @if ($errors->has('birthday'))
        <span class="help-block">
            <strong>{{ $errors->first('birthday') }}</strong>
        </span>
    @endif
</div>
<div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
    <label for="password">Senha</label>
    <input type="password" class="form-control" name="password" id="password" placeholder="Senha">
    @if ($errors->has('password'))
        <span class="help-block">
            <strong>{{ $errors->first('password') }}</strong>
        </span>
    @endif
</div>
<div class="form-group{{ $errors->has('password_confirmation') ? ' has-error' : '' }}">
    <label for="password_confirmation">Confirmar senha</label>
    <input type="password" class="form-control" name="password_confirmation" id="password_confirmation" placeholder="Confirmar senha">
    @if ($errors->has('password_confirmation'))
        <span class="help-block">
            <strong>{{ $errors->first('password_confirmation') }}</strong>
        </span>
    @endif
</div>
<div class="form-group">
    <div class="row">
        <div class="col-md-6">
            <label for="avatar">Avatar</label>
            <input type="file" id="avatar" name="avatar" value="{{ isset($user) ? $user->avatar : old('avatar') }}">
            <p class="help-block">Selecione uma imagem para o avatar do usuário.</p>
            @if ($errors->has('avatar'))
                <span class="help-block">
                    <strong>{{ $errors->first('avatar') }}</strong>
                </span>
            @endif
        </div>
        <div class="col-md-6">
            @if(isset($user->avatar_url))
                <img src="{{$user->avatar_url}}" style="width: auto; height: 195px;" class="img-circle" />
            @endif
        </div>
    </div>
</div>
<button type="submit" class="btn btn-default">Salvar</button>

resources/views/users/index.blade.php
@extends('template')

@section('main')
    <div class="text-center">
        <h2>Lista de usuários</h2>
    </div>
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
    <form no-validate class="form-horizontal" method="GET" action="{{ route('users.index') }}">
        <div class="form-group">
            <label for="document">Pesquisar</label>
            <input type="text" class="form-control" name="search" id="search" placeholder="Pesquisar" value="{{ ($search) ?: '' }}">
        </div>
    </form>
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Nome</th>
                    <th>E-mail</th>
                    <th>Cpf</th>
                    <th>Data de nascimento</th>
                    <th>avatar</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach($users as $user)
                    <tr>
                        <td>{{ $user->name }}</td>
                        <td>{{ $user->email }}</td>
                        <td>{{ $user->document }}</td>
                        <td>{{ \Carbon\Carbon::parse($user->birthday)->format('d/m/Y') }}</td>
                        <td>
                            @if($user->avatar_url)
                                <button class="avatar btn btn-default" href="{{$user->avatar_url}}">Avatar</button>
                            @endif
                        </td>
                        <td><a class="btn btn-default" role="button" href="{{ route('users.edit', $user->id) }}">Editar</a></td>
                    </tr>
                @endforeach
            </tbody>
        </table>
        <div class="text-center">
            {{ $users->links() }}
        </div>
    </div>
    <div class="modal fade" id="imagemodal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog" data-dismiss="modal">
            <div class="modal-content"  >
                <div class="modal-body">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                     <img src="" class="imagepreview" style="width: 100%;" >
                </div>
            </div>
        </div>
    </div>
@stop

@section('scripts')
    <script type="text/javascript">
        $(function() {
            $('.avatar').on('click', function() {
                $('.imagepreview').attr('src', $(this).attr('href'));
                $('#imagemodal').modal('show');
            });
        });
    </script>
@stop